version: '2'

networks:
  bridge:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      -  'MONGODB_USER=mongo' 
      -  'MONGODB_PASS=mongo123'
    volumes:
      - 'mongodb-data:/data/db'
    ports:
      - '27017:27017'
    command: mongod --smallfiles  

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=mongo'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=mongo123'
    links:
      - 'mongodb:mongo'
    ports:
      - '8081:8081'

volumes:
  mongodb-data: {}
